[package]
name = "guessing_game"
version = "0.1.0"
author = "Favour Chukwuedo"
edition = "2021"
readme = "README.md"
default-run = "cargo run"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
